name: stock_market
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_database: ^10.2.1
  firebase_auth: ^4.6.1
  firebase_storage: ^11.2.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.7.1
  web_socket_channel: ^2.4.0
  provider: ^6.0.5
  http: ^1.1.0
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
